apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  name: stackrox-secured-cluster-services
  namespace: rhacs-operator
spec:
  clusterName: local-cluster
  sensor:
    resources:
      requests:
        cpu: 100m